export const Assets = {
  salaryseNameLogo: "/images/salaryse_name_logo.png",
  cubLogo: "/images/cub_logo.png",
  cubSalaryDayRewards: "/images/cub_salary_day_rewards.png",
  cubLoungeAccess: "https://assets.salaryse.com/salaryse_web/icons/12_lounge_access.webp",
  cubForexRewards: "https://assets.salaryse.com/salaryse_web/icons/one_percent_forex.webp",
  indianFlag: "/images/indian_flag.png",
  cubSdb25: "https://assets.salaryse.com/cub/cvp/salary_day_reward_25_0.webp",
  cubBgBlueBlur: "/images/cub_bg_blue_blur.png" ,
  cubFivePercentRewards: "https://assets.salaryse.com/cub/cvp/5_percent_rewards.webp",
  cubTenPercentRewards: "https://assets.salaryse.com/cub/cvp/10_percent_rewards.webp",
  cubLifetimeFree: "https://assets.salaryse.com/cub/cvp/virtual_ltf.webp",
  cubRadialGradientMtb: "/images/cub_radial_gradient_mtb.webp",
  cubRadialGradientTtm: "/images/cub_radial_gradient_ttm.webp",
  cubGradientMtb: "/images/cub_gradient_mtb.webp",
  cubGradientTtm: "/images/cub_gradient_mtb.webp",
  cubCvpIllustration1: "https://assets.salaryse.com/salaryse_web/icons/cub_cvp_illustration_3.webp",
  cubCvpIllustration2: "https://assets.salaryse.com/salaryse_web/icons/cub_cvp_illustration_1.webp",
  cubCvpIllustration3: "https://assets.salaryse.com/salaryse_web/icons/cub_cvp_illustration_2.webp",
  rightIcon: "https://assets.salaryse.com/line_icons/chevron_right.svg",
  cubAlreadySignupGraphic: "https://assets.salaryse.com/salaryse_web/icons/cub_already_signup_graphic.webp",
  playStoreIcon: "https://assets.salaryse.com/salaryse_web/icons/play_store_ic.svg",
  appStoreIcon: "https://assets.salaryse.com/salaryse_web/icons/app_store_ic.svg"
} as const;